import type { MetadataRoute } from 'next'
import { getSiteUrl } from '@/socle/config/site'

/**
 * /robots.txt — generated by Next.js from this file.
 *
 * Baseline Socle policy (per docs/SEO_RULES.md):
 *   - Allow the public root.
 *   - Block the admin shell, API endpoints, dev tooling, and the login page.
 *   - Point to the sitemap so crawlers discover content via the canonical list.
 *
 * The future SEO module may extend this list (e.g. block paginated tag pages
 * past page N). It must not weaken these defaults.
 */
const PRIVATE_PATHS: ReadonlyArray<string> = [
  '/admin',
  '/admin/',
  '/api',
  '/api/',
  '/dev',
  '/dev/',
  '/login',
]

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: [...PRIVATE_PATHS],
    },
    sitemap: `${getSiteUrl()}/sitemap.xml`,
  }
}
