import type { MetadataRoute } from 'next'
import { getSiteUrl } from '@/socle/config/site'

/**
 * /sitemap.xml — generated by Next.js from this file.
 *
 * Baseline Socle policy (per docs/SEO_RULES.md):
 *   - List the public homepage only.
 *   - The future SEO module replaces or extends this with dynamic entries
 *     from CMS / Blog / module pages (with their per-content lastModified).
 *
 * Returning a single static entry guarantees a valid sitemap is served from
 * day one, even before the SEO module exists. Crawlers will still discover
 * additional pages via in-page links.
 */
export default function sitemap(): MetadataRoute.Sitemap {
  const url = getSiteUrl()
  return [
    {
      url,
      lastModified: new Date(),
      changeFrequency: 'weekly',
      priority: 1,
    },
  ]
}
